### ISSUE TITLE
Website Development Framework Discussion

### ISSUE THREAD

**Issue by limichange** [OneKeyHQ/portal#1]
Hi, everyone 😎.

The homepage design is almost finalized and ready to start development. but before development, we need to talk about the structure of the project and the development technology selection.

Are there any strict requirements?

**Comment by rayston92** [comment]
@loaddss 

Apparently we need cotribution doc to help community contributor get onboard, including lint, CI testing requiremnts, etc.

Here's a good example to follow: https://github.com/trezor/trezor-firmware/blob/master/docs/misc/contributing.md

**Comment by rayston92** [comment]
@limichange 

Hi Lim, I'm glad we're finally getting into the Coding phase, we do have to decide on the architecture of the site and the way to use some stylesheets, considering the maintainability of the site in the future, do you have any suggestions for discussion (like which unstyled UI-Lib we use as a base).

cc @loaddss

**Comment by limichange** [comment]
Just call me `Limi` or `cm` or `厘米` Thanks♪(･ω･)ﾉ. 

Thank you for your responses. We had some discussions on slack. Let me synchronize the discussion result.

## technology
- eslint
- prettier
- gatsby
- emotion (css in js)
- no grid
- typescript

**Comment by limichange** [comment]
Get it, now we have an outline, and now we can start doing something. Don't worry, I've used these technology before.

**Comment by limichange** [comment]
The project initialization is ready, please [check it](https://github.com/OneKeyHQ/portal/pull/2).

**Comment by limichange** [comment]
Thanks for the code review, now the project initialization is done, so closed this issue. Happy cooperation.
