### ISSUE TITLE
二级页标题字号统一

### ISSUE THREAD

**Issue by imneway** [OneKeyHQ/portal#103]
备忘下，1440下标题字号统一为 text-1000(60pt)，1920 下统一为 text-1100(72pt)。刚发现之前设计稿字号没统一。

**Comment by limichange** [comment]
`二级页标题` 是指 `Hero的标题`和每页里的各个 `Section的标题`么

**Comment by imneway** [comment]
> `二级页标题` 是指 `Hero的标题`和每页里的各个 `Section的标题`么

上面写的很早了，当时讲的是 Hero 标题字号统一。

刚整理了设计稿，更新下规则：

1. 1440下：
    - 左文右图和纯文字 hero 标题统一是  text-1000
    - 全屏图片 hero （如首页和 Enterprise ）标题是 text-900
  
2. 1920 下 hero 标题和下面每个 section 大标题都比 1440 大一号。（卡片标题、小标题等不用变）
我在下面贴了全部页面要放大的标题和一些注释，可参考，（注意 shop 页面有个例外，有 3 个小标题也要放大）：
![CleanShot 2022-07-20 at 10 35 16@2x](https://user-images.githubusercontent.com/869101/179885961-f974ab20-43a9-4489-b331-c393b4f4839b.png)
![CleanShot 2022-07-20 at 10 36 19@2x](https://user-images.githubusercontent.com/869101/179886034-424405e0-f00e-4c9a-bf22-b527d35251eb.png)
![CleanShot 2022-07-20 at 10 36 44@2x](https://user-images.githubusercontent.com/869101/179886049-dc196e08-4ce8-4e0d-89ab-597b6a3a5c9c.png)
![CleanShot 2022-07-20 at 10 37 06@2x](https://user-images.githubusercontent.com/869101/179886059-ce464b51-9997-4616-ab6c-b1e7149703b2.png)
![CleanShot 2022-07-20 at 10 38 03@2x](https://user-images.githubusercontent.com/869101/179886067-f7e02bf0-5f16-4d07-87e7-60bcde2c28bc.png)
![CleanShot 2022-07-20 at 10 38 53@2x](https://user-images.githubusercontent.com/869101/179886074-6209576d-3766-4b11-b375-508b21249c5c.png)
![CleanShot 2022-07-20 at 10 39 45@2x](https://user-images.githubusercontent.com/869101/179886091-5ad8e741-165b-4699-8fea-37d8188dc762.png)
![CleanShot 2022-07-20 at 10 40 51@2x](https://user-images.githubusercontent.com/869101/179886106-e5cd733a-b39c-4412-9e59-4b894b055704.png)

**Comment by limichange** [comment]
https://onekey-portal-git-fix-issue-103-104-limichange.vercel.app/

`全屏图片 hero （如首页和 Enterprise ）标题是 text-900` 这个有点迷糊了……我先和其他 hero 里的标题一样响应式大小了，900 的话就乱了，需要重新确认一下这个地方各个响应式具体大小。

**Comment by imneway** [comment]
ok，统一也可以
