### ISSUE TITLE
Fill EIPs content

### ISSUE THREAD

**Issue by limichange** [OneKeyHQ/portal#127]
@loatheb The EIPs data needs to be filled in here.

https://github.com/OneKeyHQ/portal/blob/main/src/components/pages/EIPs/suggestList.ts#L3-L19

**Comment by loatheb** [comment]
试试这个 `https://fiat.onekeytest.com/config/eips` ，只写了一些主要的

**Comment by limichange** [comment]
# Refs

- https://github.com/OneKeyHQ/portal/pull/265
