### ISSUE TITLE
Fill crypto page data

### ISSUE THREAD

**Issue by limichange** [OneKeyHQ/portal#128]
@loatheb  The crypto page data needs to be filled in here.

https://github.com/OneKeyHQ/portal/blob/main/src/components/pages/Cryptos/CryptosTable/suggestList.ts#L3-L25

**Comment by loatheb** [comment]
[https://fiat.onekeytest.com/config/chains](https://fiat.onekeytest.com/config/chains)  试试这个 API，到时候生产环境需要切换 endpoint
