### ISSUE TITLE
产品页序列帧动效细节

### ISSUE THREAD

**Issue by imneway** [OneKeyHQ/portal#158]
@limichange 序列帧整理好了，一些细节比较多，我就在这儿开个文档解释下，你看有没什么不明白的可以随时沟通。

Demo 视频：
https://www.dropbox.com/preview/Projects/OneKey/Demos/Product%20-%20mini%20v2.mp4
https://www.dropbox.com/preview/Projects/OneKey/Demos/Product%20-%20touch%20v1.mp4

序列帧位置：
https://www.dropbox.com/home/Projects/OneKey/Animations/Output/Onekey%20Mini
https://www.dropbox.com/home/Projects/OneKey/Animations/Output/OneKey%20Touch

一些细节说明：

整体类似 zoox 首页的效果，滚动到序列帧的地方，会全屏并锁定 position-y，播放完毕后继续滑到下个序列帧并播放。

- 序列帧每帧的滚动距离是 15px，比如一段序列帧共有 60 帧，它的滚动距离就是 15x60=900px。
（下面视频里紫色的滑块就是代表 position-y）

https://user-images.githubusercontent.com/869101/177275845-623044f4-9ab3-47e9-a19f-162490080cd2.mp4

- 序列帧在锁定 position-y 之前就要提前播放了，不然有点愣，我在 demo 设定是锁定 position-y 之前 300px 开始播放。

https://user-images.githubusercontent.com/869101/177280577-28065e0e-2b06-4c02-8de5-751c949c7f0a.mp4

- 左下角的文字进入和离开时，都有淡入淡出的效果。序列帧离开时，也有淡出效果。

https://user-images.githubusercontent.com/869101/177280780-17d3dbcc-f423-4509-a377-ef8aa6a7510b.mp4

- 两段序列帧之间有 300px 的重叠（margin: -300px），避免在两段序列帧之间切换时，中间有一大段空白。
 
<img width="1191" alt="CleanShot 2022-07-05 at 16 07 03@2x" src="https://user-images.githubusercontent.com/869101/177280841-3442c2dc-5078-4bea-af50-50df39497a3e.png">

**Comment by limichange** [comment]
@imneway 重叠这个地方，后面的图之间盖在前面图的上面？

**Comment by imneway** [comment]
后面的图在前面图的下面（被前面图盖着），然后结合上一点的前面图移走时淡出效果来避免重影的问题。

**Comment by imneway** [comment]
https://onekey-portal.vercel.app/products/onekey-touch-hardware-wallet/
刚看了下这个版本，有这些反馈：
- 滚动速度有点快，可能还没改好。
- 三个特性之间的切换是直接切的，不是上下平铺，看着有点跳，这个估计也是没弄完。
- 占位图最后加一下，一开始没刷出来白的一片不太好。

**Comment by limichange** [comment]
需要重新写一个 canvas 播放器，没切换是因为现在这个播放器是单个序列帧播放的，没法做到切换，而且占位也需要独立一个图层放。是先放这个版本，还是完全改好后再放？

**Comment by imneway** [comment]
可以先放这个版本
重写播放器会很折腾吗，需不需要考虑我直接补全上下移动的过渡帧之类的 workaround 方法？

**Comment by limichange** [comment]
如果就这一次的话，直接补上过渡帧就最简单，不用改代码了。

**Comment by limichange** [comment]
先放这个，但更泛用的播放器感觉还是要写。

**Comment by imneway** [comment]
OK，放过渡帧的话体积估计也是个挑战。
btw 现在序列帧压缩后的体积有多大？我再尝试缩减下尺寸和图片数量

**Comment by limichange** [comment]
改用 webp 了，所以基本也没法减体积了。
193 requests
6.0 MB transferred
5.9 MB resources
Finish: 5.49 s
DOMContentLoaded: 289 ms
Load: 450 ms

**Comment by imneway** [comment]
cool，6MB 听起来很理想了。我之前想着要不要跳帧之类的方法来减体积。

**Comment by limichange** [comment]
https://onekey-portal-git-feature-keys-limichange.vercel.app/

lite 的内容一起更新了

**Comment by imneway** [comment]
好一些了，还可以再慢一点（50% 左右？）。另外上下滑动切换还是要加上哈，没有上下滑动的话三个特性的切换比较乱。

**Comment by imneway** [comment]
下面的图不需要淡入，但上面的图一定要透明度淡出。因为两个产品都是第三个图边界明显，所以靠这样来解决。

**Comment by limichange** [comment]
https://onekey-portal-git-feature-keys-limichange.vercel.app/products/onekey-mini-hardware-wallet/

**Comment by imneway** [comment]
上下的图在 y 轴上还是上下平铺的关系哈，只是它们重叠了一部分，紧凑些:  
<img width="779" alt="image" src="https://user-images.githubusercontent.com/869101/178240052-e8e51bd5-1959-4ad8-86b0-c6bbc65bea5b.png">

**Comment by limichange** [comment]
试过了一下，上面淡出就会空出一
![CleanShot 2022-07-11 at 18 06 37@2x](https://user-images.githubusercontent.com/1947344/178241029-ea850240-a0ce-4644-9297-02dd5af67393.jpg)
块

**Comment by imneway** [comment]
噢对，得再加个背景色 #0D1013 / #F0F1F2

**Comment by limichange** [comment]
https://onekey-portal-nlzly8k0v-limichange.vercel.app/products/onekey-touch-hardware-wallet/

**Comment by imneway** [comment]
Much better!

**Comment by imneway** [comment]
有个小 bug，加载页面后缩放窗口的话，图会跑到上面去。不过这关系不大，一般没人这么干

<img width="2602" alt="CleanShot 2022-07-11 at 18 38 56@2x" src="https://user-images.githubusercontent.com/869101/178246969-377ab452-1bb2-4efd-bd08-c68202ec5399.png">

**Comment by limichange** [comment]
https://github.com/OneKeyHQ/portal/pull/173
