### ISSUE TITLE
进入不同路由的页面时，语言应当保持一致，不应该被自动切换。

### ISSUE THREAD

**Issue by rayston92** [OneKeyHQ/portal#160]
https://user-images.githubusercontent.com/5518945/177532284-83065ad9-5221-4abe-9dfe-4d7785282724.mov

**Comment by limichange** [comment]
Because the download path (app path) is old, it is linked to he absolute url instead of being converted to the i18n path.
-----------
PR: https://github.com/OneKeyHQ/portal/pull/161
