### ISSUE TITLE
二级页订阅模块按钮颜色不对

### ISSUE THREAD

**Issue by imneway** [OneKeyHQ/portal#164]
如图，应该是黑色的
<img width="862" alt="CleanShot 2022-07-07 at 10 58 45@2x" src="https://user-images.githubusercontent.com/869101/177681291-5e9cec82-6690-456b-9d12-269a04b96323.png">

**Comment by limichange** [comment]
这个其实是 disable 状态，干脆没填 email 的时候先隐藏了

**Comment by imneway** [comment]
还是留着吧，但是黑色的

**Comment by limichange** [comment]
https://onekey-portal-qxjhls94e-limichange.vercel.app/affiliate-program
