### ISSUE TITLE
产品页底部推荐版块 Pro 卡片去掉 Hover 效果

### ISSUE THREAD

**Issue by imneway** [OneKeyHQ/portal#165]
如图，pro 还没做，所以先不加 hover 效果
<img width="542" alt="CleanShot 2022-07-07 at 10 59 55@2x" src="https://user-images.githubusercontent.com/869101/177681413-88cffc34-df50-4048-8b19-de8c7c9d5a52.png">

**Comment by imneway** [comment]
顺便给它加了个 coming soon：
https://www.figma.com/file/rqmXU2bN1c6zBDVc5TLAop/OneKey---Marketing-Website?node-id=7576%3A35994
<img width="426" alt="CleanShot 2022-07-07 at 11 02 07@2x" src="https://user-images.githubusercontent.com/869101/177681606-c6b08d4f-9fc9-4b9e-a30d-ff7bde4d235a.png">

**Comment by limichange** [comment]
https://github.com/OneKeyHQ/portal/pull/180
