### ISSUE TITLE
产品页 Focus and release 微调了间距

### ISSUE THREAD

**Issue by imneway** [OneKeyHQ/portal#166]
不紧急，之前间距不太严谨：

https://www.figma.com/file/rqmXU2bN1c6zBDVc5TLAop/OneKey---Marketing-Website?node-id=7576%3A35778

<img width="1270" alt="CleanShot 2022-07-07 at 11 03 29@2x" src="https://user-images.githubusercontent.com/869101/177681799-521ac40a-2630-45a1-b31d-b453f8fcedc6.png">

**Comment by limichange** [comment]
https://github.com/OneKeyHQ/portal/pull/176
