### ISSUE TITLE
导航中 Mini 背景色不对

### ISSUE THREAD

**Issue by imneway** [OneKeyHQ/portal#167]
参考设计稿，应该是淡灰色（深灰色是未来给 Pro 的）：
<img width="610" alt="CleanShot 2022-07-07 at 11 04 47@2x" src="https://user-images.githubusercontent.com/869101/177681884-36b28991-bbb7-4bc3-b59d-4444cbbc31ca.png">

**Comment by limichange** [comment]
https://github.com/OneKeyHQ/portal/pull/175
