### ISSUE TITLE
产品页 Multi Chain Support 有误

### ISSUE THREAD

**Issue by imneway** [OneKeyHQ/portal#168]
如图，高度需要根据设计稿还原下。另外有一行描述文字也没了。
<img width="1444" alt="CleanShot 2022-07-07 at 11 06 47@2x" src="https://user-images.githubusercontent.com/869101/177682111-9175ff74-4125-46b1-9485-cd31a8d89ff7.png">

**Comment by imneway** [comment]
补充一个：
Lite 页面不加这个卡片

**Comment by limichange** [comment]
https://github.com/OneKeyHQ/portal/pull/204
