### ISSUE TITLE
Security 页面 hero 调整

### ISSUE THREAD

**Issue by imneway** [OneKeyHQ/portal#169]
如图：
1. 右边的图更新下，做了个新的图。
2. 左边背景改成白色，之前设计稿疏忽了。

https://www.figma.com/file/rqmXU2bN1c6zBDVc5TLAop/OneKey---Marketing-Website?node-id=7167%3A34486

<img width="761" alt="CleanShot 2022-07-07 at 11 14 09@2x" src="https://user-images.githubusercontent.com/869101/177683157-ac392d71-7122-41d5-91a1-ab177011e556.png">

**Comment by limichange** [comment]
🤔 有的页面 Hero 的标题是左下角，有的是居中的，要不要统一一下？

**Comment by imneway** [comment]
这个还好，现在的规则是全屏背景标题在左下角，半屏背景的标题在左边居中。

**Comment by limichange** [comment]
https://github.com/OneKeyHQ/portal/pull/199
