### ISSUE TITLE
OneKey Lite 问题

### ISSUE THREAD

**Issue by imneway** [OneKeyHQ/portal#172]
1.  如图，前两张图有背景色的，切图漏了。
<img width="374" alt="CleanShot 2022-07-08 at 10 55 24@2x" src="https://user-images.githubusercontent.com/869101/177907941-4484af55-a5fc-4ccc-a2a2-8f13980b94de.png">

2. 第一张图的视频已经好了，可以先换上：
https://www.dropbox.com/preview/Projects/OneKey/Animations/Output/OneKey%20Lite/onekey-lite-feature-01.mp4

3. 文案有误，应为 OneKey Lite:
<img width="550" alt="CleanShot 2022-07-08 at 10 57 29@2x" src="https://user-images.githubusercontent.com/869101/177908167-9b9c0ab3-dada-45b1-8e7b-955ddea2fdd3.png">

**Comment by limichange** [comment]
https://onekey-portal-6wpyov6ud-limichange.vercel.app/products/onekey-lite-hardware-wallet/
