### ISSUE TITLE
typo, touch mkt 页面中出现的了 mini  标题

### ISSUE THREAD

**Issue by rayston92** [OneKeyHQ/portal#174]
![2022-07-09_23 02 28](https://user-images.githubusercontent.com/5518945/178114437-1284d369-4442-41ed-9069-0383467970d1.png)

**Comment by limichange** [comment]
@rayston92 这个改过了，只是似乎没部署。

**Comment by rayston92** [comment]
@loatheb plz deploy, use lamda or airplane action...

**Comment by loatheb** [comment]
已部署
