### ISSUE TITLE
typo, 3.1 Inch IPS Display (Color)

### ISSUE THREAD

**Issue by rayston92** [OneKeyHQ/portal#177]
<img width="833" alt="Screen Shot 2022-07-11 at 18 15 49" src="https://user-images.githubusercontent.com/5518945/178242938-585ecf55-e463-48fd-9691-877594d2bd76.png">

**Comment by limichange** [comment]
ok

**Comment by limichange** [comment]
Technical specifications related to the i18n will be updated  as soon as possible.
