### ISSUE TITLE
Affiliate program Hero 调整

### ISSUE THREAD

**Issue by imneway** [OneKeyHQ/portal#181]
如图，Affiliate program hero 也加上了头图，和其它版块统一。

https://www.figma.com/file/rqmXU2bN1c6zBDVc5TLAop/OneKey---Marketing-Website?node-id=7167%3A34614

<img width="541" alt="image" src="https://user-images.githubusercontent.com/869101/178397869-1236fa54-d141-4d2b-aa0a-472c3df7e49b.png">

**Comment by imneway** [comment]
图看着有点糊？

**Comment by limichange** [comment]
我都加倍导出一下

**Comment by limichange** [comment]
https://onekey-portal-b7c1t0fzz-limichange.vercel.app/affiliate-program

**Comment by imneway** [comment]
这下好了
