### ISSUE TITLE
标题文字颜色问题

### ISSUE THREAD

**Issue by imneway** [OneKeyHQ/portal#183]
以下截图标题文字都需改用 test bg 500 这个最深的颜色。

### App 页面
![CleanShot 2022-07-12 at 12 24 05@2x](https://user-images.githubusercontent.com/869101/178408155-a3da2f7e-fa50-466c-b941-cd8b800f946b.png)

### 产品页
![CleanShot 2022-07-12 at 14 32 59@2x](https://user-images.githubusercontent.com/869101/178424238-e8047c1a-2498-4a17-8e63-04f335fc98cf.png)
（上图看得有点眼花，可能有些是误伤）
![CleanShot 2022-07-12 at 12 26 04@2x](https://user-images.githubusercontent.com/869101/178408362-7a4f1be3-9417-4566-8431-f922cd7e823f.png)
![CleanShot 2022-07-12 at 12 26 24@2x](https://user-images.githubusercontent.com/869101/178408422-d1074f66-f530-4b06-8599-c3fbc472696c.png)

### Shop 页面
![CleanShot 2022-07-12 at 12 27 44@2x](https://user-images.githubusercontent.com/869101/178408634-7aaac0ca-c560-42ff-962b-6d4a14dbbab5.png)
![CleanShot 2022-07-12 at 12 28 10@2x](https://user-images.githubusercontent.com/869101/178408696-80ecbf4d-bde2-476d-88d6-1c661102aee6.png)

### Security
![CleanShot 2022-07-12 at 12 28 48@2x](https://user-images.githubusercontent.com/869101/178408739-0c7c35e6-55f2-42cf-a514-a241d266554c.png)
![CleanShot 2022-07-12 at 12 29 09@2x](https://user-images.githubusercontent.com/869101/178408764-c44258c6-27e2-4417-814d-4f4bd3c99e39.png)

### Enterprise
![CleanShot 2022-07-12 at 12 29 28@2x](https://user-images.githubusercontent.com/869101/178408800-afd65c3c-5e0c-4766-8b7a-43342880181e.png)

### Affiliate Program
![CleanShot 2022-07-12 at 12 29 48@2x](https://user-images.githubusercontent.com/869101/178408861-dc5c5229-51b7-45a5-a79b-b852f4333336.png)

### Co Branded
![CleanShot 2022-07-12 at 12 30 19@2x](https://user-images.githubusercontent.com/869101/178408909-5a629b51-5da4-44f2-8ba8-1e651ea3387b.png)
![CleanShot 2022-07-12 at 12 30 41@2x](https://user-images.githubusercontent.com/869101/178408933-1face639-d5a8-4651-8cb1-c9bdd547b3cc.png)

**Comment by limichange** [comment]
https://github.com/OneKeyHQ/portal/pull/185

**Comment by imneway** [comment]
补充几处：
![CleanShot 2022-07-12 at 17 24 47@2x](https://user-images.githubusercontent.com/869101/178457862-293ddf9f-125b-4852-8ee3-5f0f679759ce.png)
![CleanShot 2022-07-12 at 17 24 38@2x](https://user-images.githubusercontent.com/869101/178457918-e1ec8375-c8e0-4cc9-b828-8d11d3289b8a.png)
![CleanShot 2022-07-12 at 17 23 25@2x](https://user-images.githubusercontent.com/869101/178457937-7737271f-92d6-4416-abfb-9d3f28e64c0c.png)
![CleanShot 2022-07-12 at 17 22 05@2x](https://user-images.githubusercontent.com/869101/178457950-938a5727-fd85-4b74-9ca9-e20240b971e3.png)

**Comment by limichange** [comment]
https://github.com/OneKeyHQ/portal/pull/215
