### ISSUE TITLE
产品页一些文案修正

### ISSUE THREAD

**Issue by imneway** [OneKeyHQ/portal#184]
### 三个页面通用

以下均为首字母大写问题（首字母大写，其余均为小写）

![CleanShot 2022-07-12 at 14 47 46@2x](https://user-images.githubusercontent.com/869101/178426420-54ab8f6c-14ed-454a-9506-61a49fd6ccb9.png)

<img width="598" alt="CleanShot 2022-07-12 at 14 39 17@2x" src="https://user-images.githubusercontent.com/869101/178426223-4539f449-2e49-4dfa-869f-1d1befdaf7be.png">

![CleanShot 2022-07-12 at 14 48 31@2x](https://user-images.githubusercontent.com/869101/178426620-436ac15a-a28b-44eb-acac-46f9b2d14a82.png)
（第一个文案只有 Mini 需要更新）

### OneKey Min
首字母大写，其余均为小写
<img width="462" alt="CleanShot 2022-07-12 at 14 38 32@2x" src="https://user-images.githubusercontent.com/869101/178426251-039a93fb-ef0f-4038-886b-cfa0fde667c7.png">

### OneKey Touch

首字母大写，其余均为小写
<img width="426" alt="CleanShot 2022-07-12 at 14 41 44@2x" src="https://user-images.githubusercontent.com/869101/178426142-aec23777-980c-4c98-99d3-d14d8c430dc6.png">

### OneKey Lite

首字母大写，其余均为小写
<img width="558" alt="CleanShot 2022-07-12 at 14 43 23@2x" src="https://user-images.githubusercontent.com/869101/178426088-4c7ce665-da51-4297-8dd8-4533fa5f2f42.png">

**Comment by limichange** [comment]
![CleanShot 2022-07-12 at 21 28 42@2x](https://user-images.githubusercontent.com/1947344/178502920-bedcba37-d5cd-43ef-b823-fcf9ba847b63.jpg)
![CleanShot 2022-07-12 at 21 35 16@2x](https://user-images.githubusercontent.com/1947344/178502931-11257272-fc24-490c-8343-5b7f85677d85.jpg)
![CleanShot 2022-07-12 at 21 35 20@2x](https://user-images.githubusercontent.com/1947344/178502947-37a145b6-fe11-4025-b220-af9d50fc486f.jpg)
![CleanShot 2022-07-12 at 21 35 33@2x](https://user-images.githubusercontent.com/1947344/178502954-053f34f7-2e35-4656-ac27-70fa6f77e0ae.jpg)
![CleanShot 2022-07-12 at 21 35 38@2x](https://user-images.githubusercontent.com/1947344/178502959-fe733e11-99e9-42f9-9e9e-58716615d2c0.jpg)

**Comment by limichange** [comment]
https://github.com/OneKeyHQ/portal/pull/205
