### ISSUE TITLE
产品页序列帧微调

### ISSUE THREAD

**Issue by imneway** [OneKeyHQ/portal#188]
不知目前版本和倒次第二次调整相比，加快了多少？我反复试了几次，感觉目前可以再加快个 15-25% 左右。

另外往回滚不知能不能加速？比如逆向滚动速度是正向的 200-300%。如果比较折腾的话可能得考虑禁止逆向滚动……因为刚意识到购买按钮在页面顶上，如果回滚太费劲体验不太好。 😅

**Comment by limichange** [comment]
这种情况加一个返回最上的按钮在页面右下角比较合适

**Comment by imneway** [comment]
> 加快是指滚慢一些还是快一些？
滚快一些

> 这种情况加一个返回最上的按钮在页面右下角比较合适
尽量不加吧，有点复古……

**Comment by limichange** [comment]
可以试试，不确定，因为强行劫持滚动进度不知道会导致啥问题

**Comment by imneway** [comment]
其实是改回滚速度哈，不过在开发中是一回事？

**Comment by imneway** [comment]
换了个思路，加了个购买 bar 来解决，回滚速度可以不折腾了。
https://github.com/OneKeyHQ/portal/issues/207

**Comment by imneway** [comment]
@limichange 这个 Issue 里提到滚动加快一点是加过了是吧？

**Comment by limichange** [comment]
回滚速度加快么有加

**Comment by imneway** [comment]
加一版对比下？
我用鼠标手感挺好，触摸板滑动次数会比较多

**Comment by limichange** [comment]
触摸板和鼠标不一样，触摸板会和手滑动速度有些关系

**Comment by limichange** [comment]
滚动这个其实和你具体设备有关系，因为滚轮也是能调速的，只能说有一个相对的快慢。没法保证每个人一样的滑动速度，有的人如果用滚动条拖，一下子拖完就一下子过去了。

**Comment by imneway** [comment]
对，主要是我鼠标就是调过速的，哈哈。你那边感觉怎样？

**Comment by limichange** [comment]
我鼠标是段落滚轮，所以不会一下子划过去，偏慢一些。

**Comment by imneway** [comment]
嗯，如果好改的话就加快个 15% 试下吧，刚重新对比了苹果的，它还是相对利落些

**Comment by limichange** [comment]
这个不是最后一帧么？
![CleanShot 2022-07-21 at 08 34 35@2x](https://user-images.githubusercontent.com/1947344/180105212-b12d618b-54e9-4612-86ea-80a750f21df3.jpg)

**Comment by imneway** [comment]
对的，但我滚到我截图的状态就开始向上移走了，我等下清缓存再试试

**Comment by limichange** [comment]
https://github.com/OneKeyHQ/portal/pull/235
