### ISSUE TITLE
页面之间的跳转能否不要那个回滚的效果

### ISSUE THREAD

**Issue by imneway** [OneKeyHQ/portal#189]
如视频示意，在页面上滚动后，再跳到其它页面，会有点回滚到顶部的效果，最好是比较传统的跳转，没有回滚的动效。
https://user-images.githubusercontent.com/869101/178433501-cccfd344-78f0-4563-bb2d-b228c89ab9ae.mp4

**Comment by limichange** [comment]
所有滚动都关掉么？

**Comment by imneway** [comment]
对，页面间的跳转不滚动

**Comment by limichange** [comment]
https://github.com/OneKeyHQ/portal/pull/202
