### ISSUE TITLE
安全页面问题

### ISSUE THREAD

**Issue by imneway** [OneKeyHQ/portal#190]
1. 文案问题
![CleanShot 2022-07-12 at 15 34 52@2x](https://user-images.githubusercontent.com/869101/178435123-9dd017a7-d7b9-42c3-abbd-cdd82506ce70.png)

2. 第三小节刚高亮就结束了，我调整了设计稿，加长了滚动条（左边细线），滚动条在第三节文字末尾再往下延伸 300px，接着滚动条下面还有 120px margin。看这样会不会好些。
https://www.figma.com/file/rqmXU2bN1c6zBDVc5TLAop/OneKey---Marketing-Website?node-id=7170%3A39576
![CleanShot 2022-07-12 at 15 35 55@2x](https://user-images.githubusercontent.com/869101/178435298-bd77122e-ed50-4504-99c9-f6feb389acf9.png)

3. 小序号从 01 开始
![CleanShot 2022-07-12 at 15 36 40@2x](https://user-images.githubusercontent.com/869101/178435350-62af22f0-22d7-4054-96b9-2a3b2ebde747.png)

**Comment by limichange** [comment]
@imneway https://onekey-portal-o5lkp6yos-limichange.vercel.app/security 是不是这个意思？

**Comment by imneway** [comment]
对的 👌
