### ISSUE TITLE
Co branded 页面问题

### ISSUE THREAD

**Issue by imneway** [OneKeyHQ/portal#191]
如下图标注：

https://www.figma.com/file/rqmXU2bN1c6zBDVc5TLAop/OneKey---Marketing-Website?node-id=7214%3A34469

![CleanShot 2022-07-12 at 15 58 42@2x](https://user-images.githubusercontent.com/869101/178440295-f64058c2-686f-4c41-81be-e71a820e9124.png)

![CleanShot 2022-07-12 at 15 56 45@2x](https://user-images.githubusercontent.com/869101/178440272-65e438db-ddd2-430c-a044-5f2dc1971142.png)

**Comment by limichange** [comment]
https://github.com/OneKeyHQ/portal/pull/222
