### ISSUE TITLE
多语言不用全大写

### ISSUE THREAD

**Issue by imneway** [OneKeyHQ/portal#193]
希望改成首字母大写，是不是要从数据源去改？

<img width="500" alt="CleanShot 2022-07-12 at 16 17 13@2x" src="https://user-images.githubusercontent.com/869101/178443679-44873b6b-c7dd-4a2a-b751-0d1f758b8944.png">

**Comment by limichange** [comment]
![CleanShot 2022-07-12 at 16 41 45@2x](https://user-images.githubusercontent.com/1947344/178448633-9a0a3fec-6654-4fcb-928e-b725b17b3410.jpg)
按钮位置也不要大写么？

**Comment by imneway** [comment]
嗯，对的
