### ISSUE TITLE
产品页 specs 模块调整

### ISSUE THREAD

**Issue by imneway** [OneKeyHQ/portal#196]
如图，这个断点下，文字希望可以设一个行宽，比如和上面的图一样宽，然后水平居中。（文字还是居左对齐的）
<img width="917" alt="CleanShot 2022-07-12 at 16 41 50@2x" src="https://user-images.githubusercontent.com/869101/178449708-e9787247-cfed-4b9c-b44b-ea77e9ea2b03.png">

**Comment by limichange** [comment]
https://github.com/OneKeyHQ/portal/pull/203

**Comment by imneway** [comment]
cool，挺好
