### ISSUE TITLE
Affiliate program 1920 下调整

### ISSUE THREAD

**Issue by imneway** [OneKeyHQ/portal#201]
如图，1920 下，Stay in touch 和上面两个白色卡片宽度需一致。
<img width="1816" alt="CleanShot 2022-07-12 at 17 19 10@2x" src="https://user-images.githubusercontent.com/869101/178456679-a69f791a-842e-45fc-b8dc-7f89bc1b6452.png">

**Comment by limichange** [comment]
https://github.com/OneKeyHQ/portal/pull/209
