### ISSUE TITLE
产品页导航调整

### ISSUE THREAD

**Issue by imneway** [OneKeyHQ/portal#207]
加了一个购买栏，方便用户购买。这个栏在首屏滑过之后再显示（桌面则是序列帧之后显示）。
另外 Touch 没开售，就先不加……

<img width="964" alt="CleanShot 2022-07-13 at 11 14 43@2x" src="https://user-images.githubusercontent.com/869101/178643069-e5a09bc1-303f-4d8f-b23a-58168afa495e.png">

https://www.figma.com/file/rqmXU2bN1c6zBDVc5TLAop/OneKey---Marketing-Website?node-id=8033%3A35829

**Comment by limichange** [comment]
https://github.com/OneKeyHQ/portal/pull/237
