### ISSUE TITLE
商店链接问题

### ISSUE THREAD

**Issue by rayston92** [OneKeyHQ/portal#226]
<img width="600" alt="Screen Shot 2022-07-19 at 19 09 22" src="https://user-images.githubusercontent.com/5518945/179736614-ef3bc642-a038-4036-8cf2-547328b3c503.png">

**Comment by limichange** [comment]
fixed: https://github.com/OneKeyHQ/portal/pull/227

**Comment by limichange** [comment]
## Preview

https://onekey-portal-git-fix-issue-226-limichange.vercel.app/products/onekey-mini-hardware-wallet/
