### ISSUE TITLE
OneKey Lite 页面 feature 03 换个图

### ISSUE THREAD

**Issue by imneway** [OneKeyHQ/portal#238]
如图，这块是讲防水的，之前反馈不太看得出来，重新设计了一张：
<img width="858" alt="image" src="https://user-images.githubusercontent.com/869101/180378241-e239e043-9d2c-4e7e-8a86-90815a92b672.png">
<img width="763" alt="image" src="https://user-images.githubusercontent.com/869101/180378760-1388a462-2b31-41d3-ab5a-6c5febb8ad5f.png">

**Comment by limichange** [comment]
https://github.com/OneKeyHQ/portal/pull/239
