### ISSUE TITLE
App 页面 tab 调整

### ISSUE THREAD

**Issue by imneway** [OneKeyHQ/portal#242]
如图，高亮的白色变绿色，非高亮的灰色变白色（描述文字是浅灰色）。

https://www.figma.com/file/rqmXU2bN1c6zBDVc5TLAop/OneKey---Marketing-Website?node-id=7169%3A35650

<img width="983" alt="CleanShot 2022-07-24 at 16 48 11@2x" src="https://user-images.githubusercontent.com/869101/180639713-18a3cd49-9cb6-42d6-ad51-b735686b966b.png">

**Comment by imneway** [comment]
补充：
1. 第四个 tab web 改成 bridge（文案待定）
https://www.figma.com/file/rqmXU2bN1c6zBDVc5TLAop/OneKey---Marketing-Website?node-id=7169%3A35917
<img width="984" alt="CleanShot 2022-07-24 at 17 38 06@2x" src="https://user-images.githubusercontent.com/869101/180641250-c38137bd-6dd8-4e3f-b44b-80673547a4cd.png">

2. 导航栏的 App 加上 dropdown list:
https://www.figma.com/file/rqmXU2bN1c6zBDVc5TLAop/OneKey---Marketing-Website?node-id=4046%3A17107
<img width="344" alt="CleanShot 2022-07-24 at 17 36 36@2x" src="https://user-images.githubusercontent.com/869101/180641231-2b1e620c-ec16-41cd-9820-40add854f379.png">

**Comment by limichange** [comment]
![CleanShot 2022-07-25 at 06 03 15@2x](https://user-images.githubusercontent.com/1947344/180667599-40807b4d-921c-4ebb-ab52-b3572eacf35b.jpg)

这个删掉？

**Comment by imneway** [comment]
哦对的，移到第四个 Tab 去了

**Comment by limichange** [comment]
老实说，变成绿色字，tabs 的部分和上面关联性感觉也不是很强

**Comment by imneway** [comment]
他意思是不是他们会在后台更新文案，不用我们改？
<img width="327" alt="CleanShot 2022-07-26 at 20 18 27@2x" src="https://user-images.githubusercontent.com/869101/181004039-dfc57938-7354-4a55-8268-e811ff22c5e9.png">

**Comment by limichange** [comment]
对，不用管，因为这个就是下面要删掉那里那个文案，而且更新是用 i18n 平台管理的。

**Comment by imneway** [comment]
好，但那个文案放首屏太长了，我是想请他拟一个新的，我还是跟他沟通下

**Comment by limichange** [comment]
ok 那直接就说太长了，需要一个新的

**Comment by imneway** [comment]
对了，我之前发现 browser extension tab 的标题和 desktop app 的重复了，不知这个是让谁改？

<img width="568" alt="CleanShot 2022-07-27 at 15 28 36@2x" src="https://user-images.githubusercontent.com/869101/181188000-fc8ab21f-0571-4ac1-9f79-58487aac7181.png">

**Comment by limichange** [comment]
不太确定，明天改的时候看一下。

**Comment by limichange** [comment]
https://github.com/OneKeyHQ/portal/pull/244

**Comment by imneway** [comment]
我这 bridge 没有下载按钮？
<img width="1586" alt="CleanShot 2022-07-30 at 22 30 49@2x" src="https://user-images.githubusercontent.com/869101/181919030-f177d916-7e44-413d-b2d7-6d7130334971.png">

**Comment by limichange** [comment]
🌝 还在部署……你等个几分钟，我刚改完

**Comment by limichange** [comment]
> 对了，我之前发现 browser extension tab 的标题和 desktop app 的重复了，不知这个是让谁改？

这个是我弄错了，等部署后也是好的。

**Comment by imneway** [comment]
lol 好

**Comment by imneway** [comment]
有了，close 了
