### ISSUE TITLE
优化购买入口

### ISSUE THREAD

**Issue by imneway** [OneKeyHQ/portal#248]
### 商品页面
1. 移除购买数量，下单按钮改 Buy now，点击弹出下拉菜单选择商店
https://www.figma.com/file/rqmXU2bN1c6zBDVc5TLAop/OneKey---Marketing-Website?node-id=7576%3A35778

<img width="481" alt="CleanShot 2022-08-01 at 15 58 47@2x" src="https://user-images.githubusercontent.com/869101/182101313-d0a916d9-21d5-4dcd-a9a9-c245f4bab0d3.png">

2. 移动端的下拉用 action sheet。（站内其它的下拉在 mobile 也可以统一用这控件）
https://www.figma.com/file/rqmXU2bN1c6zBDVc5TLAop/OneKey---Marketing-Website?node-id=8359%3A42378

<img width="328" alt="CleanShot 2022-08-01 at 15 54 29@2x" src="https://user-images.githubusercontent.com/869101/182100543-d466b49d-c71f-4b97-9304-e6acbbca7466.png">

3. 之前加的购买 bar 同步调整
https://www.figma.com/file/rqmXU2bN1c6zBDVc5TLAop/OneKey---Marketing-Website?node-id=8033%3A35829

<img width="966" alt="CleanShot 2022-08-01 at 15 55 25@2x" src="https://user-images.githubusercontent.com/869101/182100700-79ffa32a-cd2a-417d-a6c7-eebf24800cf2.png">

4. 中文语言下，有赞的位置放最前面

### 首页
Go to shop 按钮加了图标（首页几个相同按钮统一调整）
https://www.figma.com/file/rqmXU2bN1c6zBDVc5TLAop/OneKey---Marketing-Website?node-id=4059%3A18261

<img width="522" alt="CleanShot 2022-08-01 at 15 56 29@2x" src="https://user-images.githubusercontent.com/869101/182100923-b9902ad8-150b-4eae-b04d-daa4dcd17868.png">

**Comment by imneway** [comment]
补充 Shop 页面还有个 buy 按钮
<img width="883" alt="CleanShot 2022-08-01 at 16 51 25@2x" src="https://user-images.githubusercontent.com/869101/182111221-69366853-a2f0-4967-90c4-33b6aead0fc2.png">

**Comment by limichange** [comment]
https://github.com/OneKeyHQ/portal/pull/256

先把流程改了，action sheet 等一等，有点费劲。

**Comment by imneway** [comment]
ok，没什么问题

**Comment by limichange** [comment]
……要额外写一个插件，action sheet 和 select 是完全独立的，现在要合并在一起在响应式的时候替换。

**Comment by limichange** [comment]
现在也没有现成且独立的 action sheet 的插件

**Comment by limichange** [comment]
要不 select 够用，就先砍了吧

**Comment by imneway** [comment]
可以的，我从 web app 的角度惯性思考了。
select 在移动端可以调整样式吗？padding, 字号等，让它体验上接近 action sheet。
另外 select 要考虑一下遇到窗口边界时要从另一个方向弹出，在手机和 iPad 上，select 都刚好在屏幕外面弹出，用户看不到：
![IMG_6333](https://user-images.githubusercontent.com/869101/182570294-12482c29-a7e9-4450-8542-346c8627e470.PNG)

**Comment by imneway** [comment]
或者简单点移动端统一在上面弹出来就好

**Comment by limichange** [comment]
https://onekey-portal-ipxde6q5h-limichange.vercel.app/products/onekey-mini-hardware-wallet/

你看看，移动端直接用原生的空间怎么样

**Comment by imneway** [comment]
点开后前面选中的小勾有点怪，像是选择不是跳转。能不能去掉？

**Comment by limichange** [comment]
不太行……还是明天画一个 action sheet 吧

**Comment by imneway** [comment]
mobile 下 select 从按钮上面弹出简单些？

**Comment by limichange** [comment]
<img src='https://user-images.githubusercontent.com/1947344/182764511-bc3bd2ae-0d8c-4ff0-881f-9fb013ff468e.png' width='360'>

**Comment by imneway** [comment]
💯

**Comment by limichange** [comment]
https://user-images.githubusercontent.com/1947344/182765271-121603cd-edcc-4f2b-88f4-297c164ab9eb.mp4

**Comment by limichange** [comment]
https://github.com/OneKeyHQ/portal/pull/256

**Comment by imneway** [comment]
对了 Shopify 放第一个吧

**Comment by imneway** [comment]
其他没问题
