### ISSUE TITLE
首页软件那里的白色细线又有了

### ISSUE THREAD

**Issue by imneway** [OneKeyHQ/portal#249]
如图这里
![CleanShot 2022-08-01 at 16 49 38@2x](https://user-images.githubusercontent.com/869101/182110940-0edc4ded-724a-4bf6-b0aa-29d7888a8c9e.png)

**Comment by limichange** [comment]
你这是用的哪一个浏览器看的？

**Comment by imneway** [comment]
Arc，又试了下是特定尺寸才触发，正常没有，可以忽略……
<img width="1492" alt="CleanShot 2022-08-02 at 14 23 52@2x" src="https://user-images.githubusercontent.com/869101/182306147-e9c17c68-d7f4-4fba-b6f1-33d88b992a8f.png">
<img width="1324" alt="CleanShot 2022-08-02 at 14 24 08@2x" src="https://user-images.githubusercontent.com/869101/182306165-c75e7a0f-4e18-4fce-b894-3ba661f243b2.png">

**Comment by limichange** [comment]
可能是缩放刚刚好把一个 1px 错位了，我修一下。

**Comment by limichange** [comment]
https://github.com/OneKeyHQ/portal/pull/254
