### ISSUE TITLE
导航的 product / service 下拉菜单容易收起

### ISSUE THREAD

**Issue by imneway** [OneKeyHQ/portal#250]
如视频示意，hover 后如果移出菜单容易收起，需要和 Enterprise 小菜单一样处理下 gap 。
https://share.cleanshot.com/kpQjYc

**Comment by limichange** [comment]
https://github.com/OneKeyHQ/portal/pull/253

**Comment by imneway** [comment]
有个小的 glitch，收起的时候，导航先隐藏了，导致顶部空一块
https://share.cleanshot.com/cl1DXf

**Comment by limichange** [comment]
https://onekey-portal-git-fix-issue-250-2-limichange.vercel.app/

加了一个动画延迟

**Comment by imneway** [comment]
cool，没问题了
