### ISSUE TITLE
更新 Mini 与 Touch 第三段序列帧切图

### ISSUE THREAD

**Issue by imneway** [OneKeyHQ/portal#261]
刚整理时发现原来当初序列帧我是加了一段淡入的帧来避免下图的重影问题的，后来搞忘了。。。麻烦更新下。都是更新第三段即可。

btw：两段动画都会加长 15 帧左右。

Mini 切图：https://www.dropbox.com/home/Projects/OneKey/Animations/Output/Onekey%20Mini/onekey-mini-feature-03
Touch 切图： https://www.dropbox.com/home/Projects/OneKey/Animations/Output/OneKey%20Touch/onekey-touch-feature-03

<img width="1565" alt="CleanShot 2022-08-05 at 10 35 31@2x" src="https://user-images.githubusercontent.com/869101/182989680-6d4b6ba0-83a8-478f-ac8c-db220dc14834.png">

**Comment by limichange** [comment]
分别增加到了 `92张` 和 `77张`

https://github.com/OneKeyHQ/portal/pull/262

**Comment by imneway** [comment]
👍，挺好
