### ISSUE TITLE
滚动时，详情页有明显的卡顿不连贯掉帧问题

### ISSUE THREAD

**Issue by loatheb** [OneKeyHQ/portal#272]
是否可以通过只允许展示几个关键帧的方式展示这种形态的图片

https://user-images.githubusercontent.com/18140164/185736246-71503093-2e5f-476b-b076-e246afce3ca5.mov

**Comment by limichange** [comment]
@loatheb 具体卡顿是什么类型的浏览器和系统？

**Comment by loatheb** [comment]
@limichange 都是比较新的 Chrome ，慢慢的在中间状态滚动会比较明显

**Comment by limichange** [comment]
我重新看了视频，卡顿是不是指鼠标滑动慢，画面也慢？

**Comment by limichange** [comment]
这里设计的时候为了保证加载速度，按 30 帧的图来加载的，一帧一帧的看就会顿。哪怕放个视频在这里，一秒一秒看也是掉帧的感觉。
