### ISSUE TITLE
tokens / 币种展示列表 / ventures 等遗留页面

### ISSUE THREAD

**Issue by loatheb** [OneKeyHQ/portal#273]
- https://onekey.so/ventures
- https://onekey.so/coins/btc
- https://onekey.so/invest
- https://onekey.so/coins/ltc （等）

等页面

**Comment by imneway** [comment]
根据 slack 讨论，这几个页面都可以归档了

**Comment by rayston92** [comment]
确认都可以归档，这些页面不做了。

**Comment by loatheb** [comment]
这些要下线的页面，是否可以考虑在新的官网直接去掉入口呢，这样老的项目也能完整去掉，防止后期两个项目之间的路由冲突或是其他的问题 cc @imneway

**Comment by imneway** [comment]
嗯，我们也是建议去掉的。 @rayston92 footer 链接你们看怎么整理下？之前也提到 footer 和顶部 nav 结构不对应的问题。

**Comment by rayston92** [comment]
@imneway 

去掉入口就好...

**Comment by limichange** [comment]
https://github.com/OneKeyHQ/portal/pull/292
