### ISSUE TITLE
安卓等部分浏览器，会提示版本异常

### ISSUE THREAD

**Issue by loatheb** [OneKeyHQ/portal#275]
![Screenshot_20220820_164919_com huawei browser](https://user-images.githubusercontent.com/18140164/185737223-561f1642-32ba-4d70-9b39-70a816bf3b7f.jpg)

荣耀 mate40 内置浏览器
如果是因为一些 3d 效果需要高版本浏览器，是否可以在移动端禁用效果，或着减弱 UI 的表现。

**Comment by limichange** [comment]
感觉这个浏览器可能不老，只是被魔改了认不出来。移动端已经禁用了很多东西了，感觉好像点忽略就行了。

**Comment by limichange** [comment]
@loatheb 现在这个提示已经去掉了
