### ISSUE TITLE
页面下滑流畅，往上滑容易卡主

### ISSUE THREAD

**Issue by guosaitester** [OneKeyHQ/portal#284]
页面下滑流畅，往上滑容易卡主
屏幕录制2022-08-24 下午4.00.39.mov

**Comment by guosaitester** [comment]
https://user-images.githubusercontent.com/80317810/186368575-3b974b21-2253-4ac3-aece-8da906bf53ef.mov

**Comment by limichange** [comment]
🤔 电脑是什么配置？我们之前最低是在 MacBook Pro 2017 上测试的。

**Comment by guosaitester** [comment]
MacBook Air (13-inch, 2017)

**Comment by limichange** [comment]
@guosaitester ok 我们找一下机子试一下。

**Comment by limichange** [comment]
@guosaitester 现在会在性能不太够的机器上回滚到图文显示模式

- https://github.com/OneKeyHQ/portal/pull/352
