### ISSUE TITLE
点击按钮「联系我们」没有反应

### ISSUE THREAD

**Issue by guosaitester** [OneKeyHQ/portal#286]
点击按钮「联系我们」没有反应
https://onekey.so/zh_CN/co-branded-partnership/ 
https://user-images.githubusercontent.com/80317810/186570091-9fafc36b-06f7-49e7-bff6-4948d31e2e61.mov

**Comment by limichange** [comment]
## Fixed

-  https://github.com/OneKeyHQ/portal/issues/288
