### ISSUE TITLE
产品- 硬件图片只显示一部分，没有完整显示

### ISSUE THREAD

**Issue by guosaitester** [OneKeyHQ/portal#287]
https://user-images.githubusercontent.com/80317810/186572164-5707e699-9611-446d-b1ce-48092b9ce3f5.mov

https://onekey.so/zh_CN/shop

且缺少classic 图片

**Comment by imneway** [comment]
设计是这样的，给产品一个特写比较醒目。
Classic 页面还没设计出来，所以没入口。
