### ISSUE TITLE
手机端-打开web app 是3.4.0 包

### ISSUE THREAD

**Issue by guosaitester** [OneKeyHQ/portal#289]
https://user-images.githubusercontent.com/80317810/186797867-fa7fb2e5-ac56-4133-bd77-49a9c4f9e0b0.mp4

https://onekey.so/download/

@loatheb

**Comment by loatheb** [comment]
web 这里暂时还没有启用

**Comment by limichange** [comment]
@loatheb 需要我把这个按钮禁用么？

**Comment by loatheb** [comment]
先不用，马上就启用了

**Comment by limichange** [comment]
ok, @guosaitester, please close it 🟢
