### ISSUE TITLE
手机端-下载安卓包链接不明显

### ISSUE THREAD

**Issue by guosaitester** [OneKeyHQ/portal#290]
只有文案，不容易发现这个链接

https://user-images.githubusercontent.com/80317810/186798829-a534e823-5c1e-41f5-8ea0-ad4f79883451.mp4

**Comment by limichange** [comment]
@imneway @rayston92 这个地方是当初确认的设计么？

**Comment by imneway** [comment]
改成下拉（action sheet）吧，和 Desktop 统一：

https://www.figma.com/file/rqmXU2bN1c6zBDVc5TLAop/OneKey---Marketing-Website?node-id=7169%3A36368

<img width="684" alt="CleanShot 2022-08-26 at 10 55 00@2x" src="https://user-images.githubusercontent.com/869101/186806779-4672931c-01a1-49bf-9453-ab4b105a338f.png">

**Comment by limichange** [comment]
https://github.com/OneKeyHQ/portal/pull/294
