### ISSUE TITLE
整理 Footer 链接

### ISSUE THREAD

**Issue by imneway** [OneKeyHQ/portal#291]
@rayston92 footer 整个结构有些旧了，光清理归档的链接可能还不够，我整理了一版 footer 的链接，请 reiview 看看有没要修改和补充的：

https://www.figma.com/file/rqmXU2bN1c6zBDVc5TLAop/OneKey---Marketing-Website?node-id=8670%3A44982

<img width="1062" alt="CleanShot 2022-08-26 at 10 11 58@2x" src="https://user-images.githubusercontent.com/869101/186801715-d648cad6-9ce4-4534-802d-46177ac0f705.png">

### 参考

当前 footer
<img width="1718" alt="CleanShot 2022-08-26 at 10 11 15@2x" src="https://user-images.githubusercontent.com/869101/186801681-77a44816-216f-43ec-9066-789cde662893.png">

当前导航栏
<img width="1115" alt="CleanShot 2022-08-26 at 10 13 57@2x" src="https://user-images.githubusercontent.com/869101/186801980-5d2c5251-be3b-4c73-a636-d13dc9652aa5.png">

**Comment by rayston92** [comment]
1）Supported Tokens 和 Supported Chains 有什么区别

如果 Supported Tokens 指的是下面这个页面，那我们将标题从 Supported Tokens 改成 Token List 就好。

<img width="546" alt="Screen Shot 2022-08-26 at 10 47 23" src="https://user-images.githubusercontent.com/5518945/186805801-a14c5680-9423-4f39-b575-7601748336b8.png">

2）另外 Footer 和顶部 Nav 的多处文案大小未统一，如 The developer portal 和 Enterprise Solutions 就是两种风格，我们没有偏好，只要一致就可以，plz fix。

<img width="382" alt="Screen Shot 2022-08-26 at 10 50 39" src="https://user-images.githubusercontent.com/5518945/186806136-b764d518-9fdc-4957-877d-ae94be19fcc6.png">

3）后面做 'Why OneKey'（标题还没想好）页面的时候，入口放在 Information 中，Security 的上面。

<img width="831" alt="Screen Shot 2022-08-26 at 10 52 49" src="https://user-images.githubusercontent.com/5518945/186806349-5ca361ef-3d3a-4408-b7f9-f244ce0eb161.png">

**Comment by imneway** [comment]
1. 是 Token List 页面，我改改标题。 Supported Chains 是 onekey.so/cryptos 页面
2. 好的，我们统一下
3. 好

**Comment by imneway** [comment]
@limichange footer 已更新，navigation 大小写要统一也更新下：
https://www.figma.com/file/rqmXU2bN1c6zBDVc5TLAop/OneKey---Marketing-Website?node-id=3705%3A15352

<img width="1164" alt="CleanShot 2022-08-26 at 11 45 56@2x" src="https://user-images.githubusercontent.com/869101/186813187-8a9c2c4f-9642-4876-96de-8e43c2d88ace.png">
<img width="860" alt="CleanShot 2022-08-26 at 11 46 08@2x" src="https://user-images.githubusercontent.com/869101/186813213-74242277-54b3-428e-993a-3eac0db4d2d1.png">
<img width="955" alt="CleanShot 2022-08-26 at 11 46 18@2x" src="https://user-images.githubusercontent.com/869101/186813231-63a9594c-77f7-4d5d-a172-f02251ad0c9d.png">

**Comment by limichange** [comment]
https://github.com/OneKeyHQ/portal/pull/292

**Comment by imneway** [comment]
漏了一个：Support Tokens 改成 Token List

**Comment by limichange** [comment]
https://onekey-portal-88qlkzl3n-limichange.vercel.app/
