### ISSUE TITLE
tokens和cryptos 链接进入的是同一个页面

### ISSUE THREAD

**Issue by guosaitester** [OneKeyHQ/portal#293]
https://user-images.githubusercontent.com/80317810/187113651-195364cb-eb06-44c4-a31d-4a8be5d22eb5.mov

https://onekey.so/zh_CN/cryptos/
https://onekey.so/zh_CN/tokens/

Token List 页面没有了

**Comment by limichange** [comment]
https://github.com/OneKeyHQ/portal/pull/295, @rayston92
