### ISSUE TITLE
「联系我们」按钮-点击没反应

### ISSUE THREAD

**Issue by guosaitester** [OneKeyHQ/portal#297]
「联系我们」按钮-点击没反应 
https://onekey.so/zh_CN/co-branded-partnership

https://user-images.githubusercontent.com/80317810/187116531-0ab98279-5e3d-4c16-9b6f-6797c4b2eb28.mov

**Comment by guosaitester** [comment]
这个问题以前出现过，已经解决了，现在再次出现了

**Comment by limichange** [comment]
@guosaitester 因为修复了之后要 @loatheb 部署了之后才会生效，今天部署后我再看一下。

**Comment by guosaitester** [comment]
好的
