### ISSUE TITLE
页面性能开销过大

### ISSUE THREAD

**Issue by rayston92** [OneKeyHQ/portal#299]
<img width="658" alt="Screen Shot 2022-08-29 at 14 43 48" src="https://user-images.githubusercontent.com/5518945/187139370-65a08b1c-9891-483d-9dca-bc9bbb768c77.png">

**Comment by limichange** [comment]
纯技术来讲的话，把动画元素都砍掉就降下来了，或者把高清视频和高清图片拿掉也可以降低渲染的消耗。https://www.did.id/ 基本上都是纯静态，所以消耗低。这个看取舍了。
