### ISSUE TITLE
希望在 footer 添加一个 opensource 的标记

### ISSUE THREAD

**Issue by rayston92** [OneKeyHQ/portal#301]
如图，援引自 https://www.did.id/
<img width="591" alt="Screen Shot 2022-08-29 at 14 50 59" src="https://user-images.githubusercontent.com/5518945/187140732-7f7a006d-c2f5-4dde-b791-45a29e048ec4.png">

**Comment by limichange** [comment]
@imneway

**Comment by imneway** [comment]
好的

**Comment by imneway** [comment]
@limichange 加上了：

https://www.figma.com/file/rqmXU2bN1c6zBDVc5TLAop/OneKey---Marketing-Website?node-id=0%3A1

<img width="1090" alt="CleanShot 2022-08-30 at 10 55 56@2x" src="https://user-images.githubusercontent.com/869101/187338495-9a8a22cc-3221-4b2b-98a0-415008ac8676.png">

**Comment by limichange** [comment]
@rayston92 需要加个链接连到 GitHub 么？

**Comment by limichange** [comment]
- https://github.com/OneKeyHQ/portal/pull/305
