### ISSUE TITLE
win 10 搜狗的兼容/高速模式 - 官网控件间隙很小

### ISSUE THREAD

**Issue by guosaitester** [OneKeyHQ/portal#307]
![image](https://user-images.githubusercontent.com/80317810/187848349-21c5a759-d167-4a83-b5d1-960feb10d817.png)
![image](https://user-images.githubusercontent.com/80317810/187848370-c520bf1f-4324-4516-8858-07c68b1756b3.png)
![image](https://user-images.githubusercontent.com/80317810/187848415-77be1ac9-a20a-4bc9-bb8d-668ec12573fe.png)

**Comment by guosaitester** [comment]
![image](https://user-images.githubusercontent.com/80317810/187849685-80506172-482c-4795-83d2-025aec739998.png)

**Comment by limichange** [comment]
搜狗被腾讯收购后，搜狗浏览器已经废弃了，为了安全考虑建议使用其他浏览器。
