### ISSUE TITLE
文案没有居中显示

### ISSUE THREAD

**Issue by guosaitester** [OneKeyHQ/portal#308]
![Snip20220901_89](https://user-images.githubusercontent.com/80317810/187848818-1c340fc6-3eb0-44f4-82f1-71a73cf136e5.png)
文案应该对照图片居中对齐

**Comment by limichange** [comment]
@guosaitester 这里是确认过的设计，不是排版错位。

![CleanShot 2022-09-01 at 15 17 24@2x](https://user-images.githubusercontent.com/1947344/187855019-5dec2c03-cfe6-419f-b98b-9886b4e6748c.jpg)

**Comment by guosaitester** [comment]
好 ~
