### ISSUE TITLE
缺少回到顶部的按钮

### ISSUE THREAD

**Issue by guosaitester** [OneKeyHQ/portal#312]
缺少回到顶部的按钮--只能一点点滑到顶部

https://user-images.githubusercontent.com/80317810/189293374-c56121f1-bc6c-4647-9106-609d373ca324.mov

**Comment by imneway** [comment]
这个不太必要，回到顶部不是一个频繁操作。而且我们的导航栏是固定在窗口顶部的，用户随时可以跳到其它页面。

**Comment by guosaitester** [comment]
没更新前官网有回到顶部的这个按钮，是把这个按钮取消了

**Comment by imneway** [comment]
新版就没有这个按钮了
