### ISSUE TITLE
手机端-tokenlist 页面-部分机型

### ISSUE THREAD

**Issue by guosaitester** [OneKeyHQ/portal#314]
https://user-images.githubusercontent.com/80317810/189313141-b282519c-03ca-483b-8f9b-80de060e8e2a.mp4
https://user-images.githubusercontent.com/80317810/189313156-41712849-4c51-4416-a75a-9d282a512544.mp4

华为荣耀V20   华为nova7 有问题，安卓vivo x23正常，iOS正常

**Comment by limichange** [comment]
这个情况在其他页面里有么？

**Comment by guosaitester** [comment]
https://user-images.githubusercontent.com/80317810/192075889-2f5ea687-c659-468b-939f-416ecb371d8c.mp4

最新官网，手机端其他页面正常，一开始显示仍是异常的，刷新后正常

**Comment by limichange** [comment]
tokens 页面还要改设计，等再更新了之后看一下，日期未定。
