### ISSUE TITLE
手机端-首页打开列表下-滑动页面-背景出现滑动

### ISSUE THREAD

**Issue by guosaitester** [OneKeyHQ/portal#315]
https://user-images.githubusercontent.com/80317810/189315449-305dbf80-efcf-4cab-a186-5d73464af6bf.mp4

https://user-images.githubusercontent.com/80317810/189315492-89645f8e-f958-4d64-a586-86fec206f2fb.mp4

安卓华为荣耀v20   iPhoneX

**Comment by limichange** [comment]
- https://github.com/OneKeyHQ/portal/pull/317
