### ISSUE TITLE
Edge 已经支持连接硬件钱包，红框处描述可以去掉。

### ISSUE THREAD

**Issue by rayston92** [OneKeyHQ/portal#322]
<img width="942" alt="Screen Shot 2022-09-19 at 20 32 01" src="https://user-images.githubusercontent.com/5518945/191017932-a1a9980d-fde4-48bd-bc9a-c7deae2ba66c.png">

**Comment by limichange** [comment]
## Fixed

 - https://github.com/OneKeyHQ/portal/pull/324
