### ISSUE TITLE
增加 Brave 版插件下载入口，和 Chrome 插件的链接相同（因为 Brave 自己没有商店，是用的 Chrome 商店）

### ISSUE THREAD

**Issue by rayston92** [OneKeyHQ/portal#323]
<img width="678" alt="Screen Shot 2022-09-19 at 20 33 00" src="https://user-images.githubusercontent.com/5518945/191018112-1a99936a-76ab-40c6-b0f9-600666a05231.png">

**Comment by limichange** [comment]
## Fixed 

 - https://github.com/OneKeyHQ/portal/pull/324
