### ISSUE TITLE
更新 Touch 素材

### ISSUE THREAD

**Issue by imneway** [OneKeyHQ/portal#332]
因为 touch 后盖设计调整，替换 / 补充以下素材：

1. touch 产品页首屏的图集把后盖的图加回来：
https://www.dropbox.com/preview/Projects/OneKey/C4D/renders/onekey-touch/onekey-touch-gallery-05.png
<img width="1265" alt="CleanShot 2022-09-27 at 10 26 12@2x" src="https://user-images.githubusercontent.com/869101/192417149-64006d14-abbe-474b-b8b1-cd530449782d.png">

2. shop 首屏的动画替换：
https://www.dropbox.com/preview/Projects/OneKey/Animations/Output/Shop/shop-hero-animation-compressed.mp4
<img width="1425" alt="CleanShot 2022-09-27 at 10 27 14@2x" src="https://user-images.githubusercontent.com/869101/192417282-77f4acd4-dcc6-4ef4-ab67-99bcd4514554.png">

**Comment by limichange** [comment]
## Fixed 

- https://github.com/OneKeyHQ/portal/pull/334
