### ISSUE TITLE
手机端 - 在 https://onekey.so/download 下，点击下载按钮无反应，没跳到下载页面

### ISSUE THREAD

**Issue by guosaitester** [OneKeyHQ/portal#335]
手机端在 https://onekey.so/download 下，点击下载按钮，会没有反应，没跳到下载页面
在其他页面下，点击下载按钮会跳到下载页面

https://user-images.githubusercontent.com/80317810/192484049-85db2208-60cd-4c54-bd7e-5a25cd476697.mp4

**Comment by limichange** [comment]
## Fixed

 - https://github.com/OneKeyHQ/portal/pull/338
