### ISSUE TITLE
iPhoneX - 在iPhoneX 手机左上角onekey icon 和 mini 重叠

### ISSUE THREAD

**Issue by guosaitester** [OneKeyHQ/portal#336]
https://user-images.githubusercontent.com/80317810/192486166-8bfd3728-5924-49c9-a0cb-4c9987dd1adf.mp4

https://onekey.so/shop/

左上角onekey icon 和 mini 重叠，在iPhoneX 手机出现

**Comment by limichange** [comment]
增加了图片内容边界

 - https://github.com/OneKeyHQ/portal/pull/339
