### ISSUE TITLE
点击官网最下方「投资组合」链接，进入的是web 页面

### ISSUE THREAD

**Issue by guosaitester** [OneKeyHQ/portal#340]
点击官网最下方「投资组合」链接，进入的是web 页面
暂时发现这里链接不对，其他地方「投资组合」链接是正确的

https://user-images.githubusercontent.com/80317810/192730540-f0e353ff-9aff-4cb9-8c03-a4a11155f2e0.mov

**Comment by limichange** [comment]
## Fixed

 - https://github.com/OneKeyHQ/portal/pull/343

**Comment by loatheb** [comment]
以后官网上不会有那几个链接了，暂时都用 app.onekey.so 这样？

**Comment by limichange** [comment]
cc @guosaitester https://github.com/OneKeyHQ/portal/pull/343

**Comment by guosaitester** [comment]
打开投资组合🔗 仍是 web页面     https://app.onekey.so/tab/home

**Comment by limichange** [comment]
![CleanShot 2022-10-18 at 08 05 31@2x](https://user-images.githubusercontent.com/1947344/196305734-9050a4ef-4a01-4e11-b1d5-2da4a932a6b8.jpg)

**Comment by limichange** [comment]
https://app.onekey.so/tab/home @guosaitester 就是这个页面
