### ISSUE TITLE
firefox - 点击「代币列表」「支持的链」「EIPs」链接，进入新页面，无法返回

### ISSUE THREAD

**Issue by guosaitester** [OneKeyHQ/portal#341]
firefox - 点击「代币列表」「支持的链」「EIPs」链接，进入新页面后，点击返回按钮，没有返回成功
Chrome 浏览器 ， 手机端正常
点击其他链接，可正常返回

https://user-images.githubusercontent.com/80317810/192746058-796d0c00-381b-4649-9c56-99a908445972.mov

**Comment by limichange** [comment]
## Fixed

 - https://github.com/OneKeyHQ/portal/pull/344

**Comment by guosaitester** [comment]
https://user-images.githubusercontent.com/80317810/193493122-2a3f263d-4896-4a13-bd1e-f22cf832c36b.mov
返回后，页面会跳到一下

**Comment by limichange** [comment]
- https://github.com/OneKeyHQ/portal/pull/351

**Comment by guosaitester** [comment]
@limichange   点击返回后页面跳动

https://user-images.githubusercontent.com/80317810/199471778-b06b7409-e5df-4a56-98a6-13bf2ef739ba.mov
