### ISSUE TITLE
hero 区域按钮显示时机问题，加载时阻塞

### ISSUE THREAD

**Issue by rayston92** [OneKeyHQ/portal#346]
why：打开首页加载时 hero 区的按钮长时间不显示，以为是页面假死
url：onekey.so
network：大陆 WiFi 网络（全局开梯）
device：macOS/Firefox105.0.1
expected behavior：hero 区域的按钮不被动画加载进程阻塞，直接显示出来

**Comment by rayston92** [comment]
https://user-images.githubusercontent.com/5518945/193018826-43dda789-f588-450b-930c-f38d31f5bad7.mp4

**Comment by limichange** [comment]
好的，去掉淡入效果。

**Comment by limichange** [comment]
## Fixed

 - https://github.com/OneKeyHQ/portal/pull/348
