### ISSUE TITLE
21秒处页面出现自动刷新切换语言的情况

### ISSUE THREAD

**Issue by rayston92** [OneKeyHQ/portal#347]
在访问时就先对应内容，而不先加载英文页面再切换到本地语言

https://user-images.githubusercontent.com/5518945/193018826-43dda789-f588-450b-930c-f38d31f5bad7.mp4

**Comment by rayston92** [comment]
@loatheb @zhengchuang1014 看下这里怎么解决比较好。

**Comment by loatheb** [comment]
能不能这样，因为本身所有语言的 URL 都已经在服务端静态生成了，每次比如存在 cookie 或者 accet-language header 里面的语言 locale nginx 也是能读取的，能否把语言的切换，直接在服务端判断返回了，这样就能确保用户读取的都是上次选择的语言，或是 URL 指定的语言，就是服务端这里也得搭配一起改动下

**Comment by zhengchuang1014** [comment]
访问https://www.onekey.so 时候在cookie 或者header 中带入上次的选择的语言，直接301 到对应语言的url

**Comment by limichange** [comment]
@loatheb 如果想改也只能在服务端修改

**Comment by limichange** [comment]
@loatheb 你看需要我加什么，我加一下

**Comment by loatheb** [comment]
@limichange @zhengchuang1014 包含此次修复的前后端更新均已上线， @guosaitester 可以再验证下
