### ISSUE TITLE
URL 修正

### ISSUE THREAD

**Issue by rayston92** [OneKeyHQ/portal#349]
<img width="398" alt="Screen Shot 2022-10-09 at 16 38 40" src="https://user-images.githubusercontent.com/5518945/194746799-d070f869-6027-40f2-b8ed-308f0bb1b032.png">

红框处的正确 URL 是 https://www.trustpilot.com/review/onekey.so

**Comment by limichange** [comment]
- https://github.com/OneKeyHQ/portal/pull/350
