### ISSUE TITLE
导航栏滚动后高度偏高

### ISSUE THREAD

**Issue by imneway** [OneKeyHQ/portal#35]
量了下有 130+px，在笔记本屏幕上占比挺大的，需要按设计稿再缩小些（84px）。

https://www.figma.com/file/rqmXU2bN1c6zBDVc5TLAop/OneKey---Marketing-Website?node-id=4046%3A17107

<img width="946" alt="image" src="https://user-images.githubusercontent.com/869101/170218483-732a9132-cd42-4e10-9237-8d590b75f86c.png">

**Comment by limichange** [comment]
![CleanShot 2022-05-25 at 16 48 28@2x](https://user-images.githubusercontent.com/1947344/170222034-b415a8fb-52f1-4960-8393-a1f5460ed61b.jpg)

你是怎么量的？

**Comment by limichange** [comment]
🤔 我看看，属于浏览器特定 bug

**Comment by imneway** [comment]
我再 update 下，我电脑之前开启了 125% 的缩放（就是 windows 系统的那个，一般会默认开启），关闭了会好些，110px 高。另外 chrome 里高度也是一样的。

anyway 这个问题优先级可以放最后，先做其它的吧。

<img width="169" alt="image" src="https://user-images.githubusercontent.com/869101/170224761-9a15d3c9-dd34-4a59-ae7d-be960785b0ff.png">

**Comment by limichange** [comment]
![CleanShot 2022-05-30 at 15 19 08@2x](https://user-images.githubusercontent.com/1947344/170938294-26466fae-9945-4c16-abba-ddde83284675.jpg)

有空用浏览器的控制台量一下看看，几个浏览器没试出来。

**Comment by limichange** [comment]
![CleanShot 2022-05-30 at 15 21 03@2x](https://user-images.githubusercontent.com/1947344/170938649-7d8dea7e-a281-4280-be2d-2c69c5245640.jpg)

**Comment by imneway** [comment]
怪了，我这也是 88px....

![Screenshot 2022-05-30 154809](https://user-images.githubusercontent.com/869101/170943695-fb3e7580-4b23-402d-886c-be062fb389fc.png)
![Screenshot 2022-05-30 154743](https://user-images.githubusercontent.com/869101/170943701-f15273ab-1a3e-4c9e-98b1-c34a4b80ed92.png)
![Screenshot 2022-05-30 154719](https://user-images.githubusercontent.com/869101/170943706-c414be43-a2bf-47ce-8646-c7324a2d2c07.png)

**Comment by imneway** [comment]
可能整个浏览器都 scale up 了 :thinking_face:

**Comment by imneway** [comment]
先关了，我发现我的 PC 所有用浏览器内核的程序都是放大的，包括 slack / figma。找天去小米之家看看。
