### ISSUE TITLE
Safari 访问时内容溢出

### ISSUE THREAD

**Issue by rayston92** [OneKeyHQ/portal#353]
<img width="1606" alt="Screen Shot 2022-10-19 at 15 27 47" src="https://user-images.githubusercontent.com/5518945/196624958-dbddf02c-1fe9-42e7-a078-c3d4641892ac.png">

如图，在 Safari 浏览器中访问 onekey.so 时的效果

**Comment by limichange** [comment]
## Fixed
- https://github.com/OneKeyHQ/portal/pull/354
