### ISSUE TITLE
第二屏序列帧的图片在小窗口需要下移些

### ISSUE THREAD

**Issue by imneway** [OneKeyHQ/portal#36]
如图，刚发现非大屏下，右边图片上方会被导航盖住，需要下移一些，比如相对导航以外的高度居中？

<img width="946" alt="image" src="https://user-images.githubusercontent.com/869101/170218483-732a9132-cd42-4e10-9237-8d590b75f86c.png">

**Comment by limichange** [comment]
可以，我看看怎么写

**Comment by limichange** [comment]
https://home-frames-player--onekey-website.netlify.app/
