### ISSUE TITLE
此处内容消失

### ISSUE THREAD

**Issue by rayston92** [OneKeyHQ/portal#364]
<img width="1164" alt="Screenshot 2022-10-26 at 1 40 46" src="https://user-images.githubusercontent.com/5518945/197844296-2122bb23-85f6-4ee5-81c4-7219b36f4b3d.png">

**Comment by rayston92** [comment]
in chinese

**Comment by limichange** [comment]
## Fixed

 - https://github.com/OneKeyHQ/portal/pull/365
