### ISSUE TITLE
官网- token - 添加TRX网络token，已经切换TRX网络了，添加token时仍然提示切换TRX网络

### ISSUE THREAD

**Issue by guosaitester** [OneKeyHQ/portal#383]
官网- token - 添加TRX网络token，已经切换TRX网络了，添加token时仍然提示切换TRX网络

https://user-images.githubusercontent.com/80317810/204434169-7c6d9b6f-4c34-4baf-a84a-b24dd111f86c.mov

**Comment by limichange** [comment]
## Fixed 

 - https://github.com/OneKeyHQ/portal/pull/384

**Comment by limichange** [comment]
这个等下次部署就好了，可以下周的时候再看一下。

**Comment by limichange** [comment]
最新部署已经修改好了
