### ISSUE TITLE
How to integrate lokalise?

### ISSUE THREAD

**Issue by limichange** [OneKeyHQ/portal#4]
Since there are many ways to integrate it, we need to make sure how to do it.

These are some of the methods I found out.

## GitHub  Ingration
<img width="300" alt="image" src="https://user-images.githubusercontent.com/1947344/164180231-221b47ba-899f-42ce-b0dc-57f100868785.png">

## Downloads translate file directly
<img width="300" alt="image" src="https://user-images.githubusercontent.com/1947344/164180542-a2411c58-79bd-40be-829d-3be676e8190a.png">

## Lokalise node API
https://www.npmjs.com/package/@lokalise/node-api
<img width="300" alt="image" src="https://user-images.githubusercontent.com/1947344/164180675-f0872747-7416-42e6-88bc-fb7b4457c451.png">

**Comment by loaddss** [comment]
Currently we can "Downloads translate file directly", we can use more advanced method later.

**Comment by limichange** [comment]
ok, I will create a PR to try integrate lokalise with its download files.

**Comment by rayston92** [comment]
This issue shall be closed since we've achieved consensus.
