### ISSUE TITLE
移动端导航栏处理

### ISSUE THREAD

**Issue by imneway** [OneKeyHQ/portal#46]
1. 滚动后高度缩小为 72px，之前漏说了。（麻烦的话就统一缩小到 72px 吧，移动端交互可以简化些）
2. 背景加上模糊效果（麻烦的话就移动端统一用白色背景，也是可以简化）

<img width="728" alt="image" src="https://user-images.githubusercontent.com/869101/170469700-57a515a1-9726-49b5-ab4c-8528ff32d9d9.png">

**Comment by limichange** [comment]
https://fix-hero-style--onekey-website.netlify.app/
