### ISSUE TITLE
Why choose onekey 切图更新

### ISSUE THREAD

**Issue by imneway** [OneKeyHQ/portal#48]
第四张图有更新：

https://www.figma.com/file/rqmXU2bN1c6zBDVc5TLAop/OneKey---Marketing-Website?node-id=3635%3A15974

<img width="203" alt="image" src="https://user-images.githubusercontent.com/869101/170618734-fd2753ea-4502-4634-9d8e-cbb8d637f86d.png">

**Comment by limichange** [comment]
![CleanShot 2022-05-27 at 08 11 31@2x](https://user-images.githubusercontent.com/1947344/170619015-229a0f13-b81b-4166-b505-33cdd1b0a010.jpg)

ok

**Comment by limichange** [comment]
https://feature-why-section-image-update--onekey-website.netlify.app/
