### ISSUE TITLE
Maybe we could try Vercel or Netlify?

### ISSUE THREAD

**Issue by limichange** [OneKeyHQ/portal#5]
The GitHub Page is not so good. because we use the PR method of development, we need to preview every PR content, GitHub Page connot do that.

<img width="1327" alt="image" src="https://user-images.githubusercontent.com/1947344/164181954-3571ad72-cdc1-4dbe-83f3-6dd83d826e86.png">

Maybe we can try it?

### Links

- https://www.netlify.com/products/deploy-previews/
- https://vercel.com/features/previews

**Comment by rayston92** [comment]
- use Vercel for personal commit preview
- use github-pages for temp pr review
