### ISSUE TITLE
替换首页素材

### ISSUE THREAD

**Issue by imneway** [OneKeyHQ/portal#56]
之前失误了，UI 的走势图都用了暴跌的走势，涉及的图都要替换，现在都已渲染好，麻烦帮忙换一下。
需要替换的图都在 Figma Slices 区域标注了 UPDATE 标识（不止截图这些，下面还有）：
https://www.figma.com/file/rqmXU2bN1c6zBDVc5TLAop/OneKey---Marketing-Website?node-id=3944%3A16886

<img width="1103" alt="image" src="https://user-images.githubusercontent.com/869101/170823100-e116570f-cdcb-4a5d-93ae-9885f0a9ae47.png">

附注：首屏视频也要换的，但还在纠结，就是刚才在另一个 issue 里问你的（https://github.com/dinehq/portal/issues/58#issuecomment-1140240424 ），不知视频加载完再替换成静态图好不好搞。因为这个视频我想顺便压小一点，加快加载，所以还没完全定，定了再附上链接给你。

**Comment by imneway** [comment]
补充桌面端首屏素材（包括一个视频和一张结尾的图）：https://www.dropbox.com/home/Projects/OneKey/Animations

**Comment by limichange** [comment]
https://feature-update-assets--onekey-website.netlify.app/

**Comment by limichange** [comment]
🤔 都换了，不过噪点有点明显，看看能不能接受

**Comment by imneway** [comment]
是有点，又压了一次？（忘记说，首屏的已经压过了）

**Comment by imneway** [comment]
下面还有几张图要换哈
<img width="714" alt="image" src="https://user-images.githubusercontent.com/869101/170932720-d19ed4d3-3598-4981-8347-4a271a2a44c0.png">

**Comment by limichange** [comment]
ok 都更新了，实体图也更新了 
https://62946dcd3c29f4000ad0ff06--onekey-website.netlify.app/

<img width="360px" src="https://user-images.githubusercontent.com/1947344/170937532-096a1304-8b1f-4cf1-bba5-b52562fbac13.jpg">
<img  width="360px" src="https://user-images.githubusercontent.com/1947344/170937536-f20cfded-02ba-4e46-93aa-0fa0ae2f6f7e.jpg">

**Comment by imneway** [comment]
cool，我这首屏还是旧的，可能是缓存。
btw 上面这个 Mini 图的 hover 的淡入淡出效果好像改没了？

**Comment by limichange** [comment]
没了么……你录一下，我看看啥样的

**Comment by limichange** [comment]
怪了，我看看为啥。
首屏我是用的这张 `/Projects/OneKey/C4D/renders/home-hero/home-hero-motion0000.jpg`

**Comment by limichange** [comment]
...是有这个问题，我改一下。

**Comment by imneway** [comment]
对是这张，不过刚才说是不是重复压缩指的是视频和结尾的图，这两个是已经压过的。

**Comment by limichange** [comment]
https://feature-update-assets--onekey-website.netlify.app/
hover 的问题改了
> 对是这张，不过刚才说是不是重复压缩指的是视频和结尾的图，这两个是已经压过的。

这句我没太懂，看看这个链接里的是不是对的

**Comment by limichange** [comment]
> 补充桌面端首屏素材（包括一个视频和一张结尾的图）：https://www.dropbox.com/home/Projects/OneKey/Animations

或者明确说一下是哪个文件，我重新传一次，保不齐弄错了

**Comment by imneway** [comment]
就是里面的视频和图片，我这看是比本地的糊，你那边会吗？

<img width="909" alt="image" src="https://user-images.githubusercontent.com/869101/170975707-0314ebdc-2fa5-4282-936b-f09cda3e95dc.png">

**Comment by limichange** [comment]
![CleanShot 2022-05-30 at 19 00 25@2x](https://user-images.githubusercontent.com/1947344/170978792-48dd42f2-f56b-4ba8-a470-d9a6aaea416a.jpg)

😂 我感觉本地也挺糊的

**Comment by imneway** [comment]
这个高级…那我准备一下

**Comment by imneway** [comment]
全部都已压缩过

**Comment by limichange** [comment]
除了视频，有新的图要更新么？

**Comment by imneway** [comment]
同目录下的两张图也要更新的（也已压缩），其它没有了。

**Comment by limichange** [comment]
https://629610d8eb2d6f00097cee80--onekey-website.netlify.app/

**Comment by limichange** [comment]
https://6296af8b6c51890008a0fae6--onekey-website.netlify.app/
