### ISSUE TITLE
首页安全版块调整

### ISSUE THREAD

**Issue by imneway** [OneKeyHQ/portal#63]
这个不紧急，我先记着备忘：
https://www.figma.com/file/rqmXU2bN1c6zBDVc5TLAop/OneKey---Marketing-Website?node-id=4059%3A18261

1. 图片宽高比统一改为 3:4.
2. 文字小标题各断点下统一加大一号。
3. 为了应对部分断点下文字比图片高的情况，文字和图片改为底部对齐。

<img width="1254" alt="image" src="https://user-images.githubusercontent.com/869101/171314356-3e41ab17-5134-4990-bc27-16cc7f185a56.png">

**Comment by limichange** [comment]
现在这个地方有点尴尬，每个语言长度不一样，没法完全对齐，要完全对齐的话就要把右边的图比例变了

**Comment by limichange** [comment]
https://github.com/OneKeyHQ/portal/pull/211
