### ISSUE TITLE
Background image alt display issue

### ISSUE THREAD

**Issue by limichange** [OneKeyHQ/portal#68]
Occasionally the word `background` appears at the top of the hero when the home page is refreshed.

![image](https://user-images.githubusercontent.com/1947344/172625694-c0ef7611-b187-4487-bddc-d3e8488fc52a.png)

**Comment by rayston92** [comment]
word background still appears as of today when refreshing the homepage.

**Comment by limichange** [comment]
Forgot about this…… 
It will be fixed as soon as possible.

**Comment by limichange** [comment]
work 了
