### ISSUE TITLE
Meta Info

### ISSUE THREAD

**Issue by rayston92** [OneKeyHQ/portal#76]
- site title: OneKey Wallet | All-in-one crypto wallet trusted by millions.
- description: The best way to keep crypto assets safe in the industry. Your bitcoin, ethereum, solana, and other crypto assets can all be safe and secure.
- keywords: hardware wallet, defi, nft, btc, eth, near, fantom, solana, algo, starcoin, metamask, glow, trezor, ledger, safepal, keystone, imtoken, tokenpocket, rainbow wallet
- Twitter Account: OneKeyHQ

@limichange

**Comment by limichange** [comment]
@rayston92 Use one title for all pages?

**Comment by rayston92** [comment]
@limichange 

Use this title for homepage.

**Comment by limichange** [comment]
Ok, it will be updated today.

**Comment by limichange** [comment]
PR has been created and is waiting to be merged and deployed.
