### ISSUE TITLE
adding shop links

### ISSUE THREAD

**Issue by rayston92** [OneKeyHQ/portal#80]
<img width="163" alt="Screen Shot 2022-06-15 at 12 36 57" src="https://user-images.githubusercontent.com/5518945/173737772-bf69b2af-a86a-44c1-a3b6-ec2eb2600675.png">

on top the list, add:

- Amazon (Global) : https://www.amazon.com/dp/B0B2MWW2WJ
- Amazon (Japan)：https://www.amazon.co.jp/dp/B0B2MWW2WJ

**Comment by limichange** [comment]
Look like this?
![CleanShot 2022-06-15 at 13 04 15@2x](https://user-images.githubusercontent.com/1947344/173740567-7fb9a02a-e834-4897-9e2c-5e48c0c128b2.jpg)

**Comment by limichange** [comment]
## preview

https://feature-update-text-and-images--onekey-website.netlify.app/

**Comment by rayston92** [comment]
LGFM, ready to go.
