### ISSUE TITLE
html tag display issue

### ISSUE THREAD

**Issue by rayston92** [OneKeyHQ/portal#81]
<img width="344" alt="Screen Shot 2022-06-15 at 12 45 42" src="https://user-images.githubusercontent.com/5518945/173738615-398c1565-3435-4fdc-b5eb-b76e67135373.png">

**Comment by limichange** [comment]
https://feature-update-text-and-images--onekey-website.netlify.app/beta/download/?client=desktop

**Comment by rayston92** [comment]
LGFM, ready to go.
