### ISSUE TITLE
shadow issue

### ISSUE THREAD

**Issue by rayston92** [OneKeyHQ/portal#82]
<img width="299" alt="Screen Shot 2022-06-15 at 12 46 51" src="https://user-images.githubusercontent.com/5518945/173738720-fca7715f-a0f0-4a97-b7da-1ae44aea3a6e.png">

**Comment by limichange** [comment]
## preview

https://feature-update-text-and-images--onekey-website.netlify.app/beta/download/?client=mobile

**Comment by rayston92** [comment]
LGFM, ready to go.
