### ISSUE TITLE
can't change number

### ISSUE THREAD

**Issue by rayston92** [OneKeyHQ/portal#84]
<img width="355" alt="Screen Shot 2022-06-15 at 17 03 53" src="https://user-images.githubusercontent.com/5518945/173788670-4fe4d2fa-0e33-43c0-8a95-78da2fd715f5.png">

**Comment by limichange** [comment]
https://github.com/OneKeyHQ/portal/pull/89

Will post as soon as possible.

**Comment by limichange** [comment]
@rayston92 this 🌝
