### ISSUE TITLE
placeholder img should be replaced

### ISSUE THREAD

**Issue by rayston92** [OneKeyHQ/portal#85]
<img width="1051" alt="Screen Shot 2022-06-15 at 17 06 29" src="https://user-images.githubusercontent.com/5518945/173789059-676f896a-8a4b-4f61-93b7-95a52f6ae128.png">

**Comment by limichange** [comment]
The new design has been checked and will be uploaded today.
![CleanShot 2022-06-16 at 11 26 10@2x](https://user-images.githubusercontent.com/1947344/173984624-ccbab0cc-fe16-4a48-b084-8480ccf09cd2.jpg)

**Comment by limichange** [comment]
🧑‍🔧 Image has been updated, need to wait for the purchase page to complete.
