### ISSUE TITLE
change all "Launch App" to "Free Download" and redirect to download page

### ISSUE THREAD

**Issue by rayston92** [OneKeyHQ/portal#86]
<img width="303" alt="Screen Shot 2022-06-15 at 21 30 55" src="https://user-images.githubusercontent.com/5518945/173840089-2f8f8ecb-87c9-42bb-882d-b03d79c893be.png">
<img width="452" alt="Screen Shot 2022-06-15 at 21 31 00" src="https://user-images.githubusercontent.com/5518945/173840107-3534683d-e927-44f0-8d0f-2410d1d3c8fa.png">
<img width="515" alt="Screen Shot 2022-06-15 at 21 31 02" src="https://user-images.githubusercontent.com/5518945/173840120-ade1b6aa-8a49-41a8-939d-4540c94c063b.png">
<img width="413" alt="Screen Shot 2022-06-15 at 21 31 06" src="https://user-images.githubusercontent.com/5518945/173840126-38c9e30f-721c-4ebd-a385-19350fb30a60.png">
<img width="401" alt="Screen Shot 2022-06-15 at 21 30 25" src="https://user-images.githubusercontent.com/5518945/173840135-8b9b274b-8420-48ad-a5de-04493852085f.png">

**Comment by limichange** [comment]
(゜◇゜)ゞ

<img width="1360" alt="image" src="https://user-images.githubusercontent.com/1947344/174435432-f6dc6dfa-b34e-46c0-9bdd-092f272eb305.png">


<img width="596" alt="image" src="https://user-images.githubusercontent.com/1947344/174435401-8fa7caca-7c88-4cf2-b1b8-c9582f6fcd95.png">


<img width="663" alt="image" src="https://user-images.githubusercontent.com/1947344/174435447-8846201f-9358-4203-9b27-1568b31a2996.png">

<img width="660" alt="image" src="https://user-images.githubusercontent.com/1947344/174435465-8c4a3705-13df-4541-b912-57efb653fb34.png">

**Comment by rayston92** [comment]
@limichange 

Thanks ❤️
